apiVersion: v2
name: iris-healthcare-integration-demo
description: This demo shows how easy it is to integrate an Electronic Medical Record system that is sending HL7 messages with AWS. 
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: amd64-version-1.2.0


annotations:
  intersystems/sds-title: iris-healthcare-integration-demo
  intersystems/sds-organization: InterSystems Corporation
  intersystems/sds-category: core,database

