apiVersion: v1
secrets:
- field: requiredSecrets.intersystemsContainerRegistrySecret
  type: image-pull-secret
  subType: containers.intersystems.com
  reason: These are the credentials to authenticate with containers.intersystems.com
externalServicesDeclaration:
  - name: irisHealthcareIntegrationService
    type: loadBalancer
    hostnameChartField: irisHealthcareIntegrationService.hostname
    loadBalancerPortChartField: irisHealthcareIntegrationService.port
    enabled:  false
    enabledChartField:  irisHealthcareIntegrationService.enabled
    label:  
    description:

compute:
  computeSpecs:
  - name: irisHealthcareIntegrationDemo
    label:  iris healthcare integration demo
    categoryFilter: CO,MO,GP
    minCPU: 2
    minRAM: 4
    nodeSelectorField:  compute.irisHealthcareIntegrationDemo.main.nodeTypeSelector
    cpuRequestField:  compute.irisHealthcareIntegrationDemo.main.cpu
    memoryRequestField: compute.irisHealthcareIntegrationDemo.main.memory
    help: Specifies how many cores and how much memory the dedicated node will have  
